# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Musgravite' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Musgravite
	# Google Pods
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	# UI Pods
	pod 'BulletinBoard'
	pod 'SVProgressHUD'
	# Networking Pods
	pod 'SDWebImage'
	pod 'Alamofire'
end
